### ISSUE TITLE
Create a Figma Mockup for the Search Results Page

### ISSUE THREAD

**Issue by Jazzyb21** [VU-Code-For-Good/farmersmarkets-for-all#34]
> As a designer,
> I would like to create a Figma mockup for the Search Results page
> So that the development team can have a visual representation of the page and work on its implementation.

AC:
Create a Figma file for the Search Results page.
The Figma file should include all the necessary components of the Search Results page such as, search results list, pagination, and other relevant components.
The Figma file should be shared with the development team and stakeholders for feedback.

**Comment by Mechasparrow** [comment]
[Search Results.pdf](https://github.com/Veterans-United-Code-For-America/farmersmarkets-for-all/files/11467138/Search.Results.pdf)

**Comment by Mechasparrow** [comment]
TODO: create PR for mockups folder
