### ISSUE TITLE
 Figma Mockup for Home Search Page

### ISSUE THREAD

**Issue by michael-navazhylau-vu** [VU-Code-For-Good/farmersmarkets-for-all#4]
> As a user of our application,
> I want to have a visually appealing home search page,
> So that I can easily search for properties.

AC:

Create a Figma mockup of the Home Search Page.
The Figma design should include a search bar,
The design should be visually appealing and easy to use.
The design should be consistent with the branding guidelines of our application.
The design should be accessible and responsive for users with different devices and screen sizes.
Get feedback from the design team and stakeholders before proceeding with the implementation.

Database Tables:
N/A

API Endpoints:
N/A

**Comment by Mechasparrow** [comment]
[Search Home Page.pdf](https://github.com/Veterans-United-Code-For-America/farmersmarkets-for-all/files/11467140/Search.Home.Page.pdf)

**Comment by Mechasparrow** [comment]
TODO: PR for mockups folder

**Comment by Mechasparrow** [comment]
https://github.com/VU-Code-For-Good/farmersmarkets-for-all/pull/42
